export const appTypes = {
  //FOR GETTING ALL PRODUCTS
  FETCH_ALL_PRODUCTS: "FETCH_ALL_PRODUCTS",
  SET_ALL_PRODUCTS: "SET_ALL_PRODUCTS",

  //OR STORIGN CART PRODUCTS
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_CART: "REMOVE_CART",
  UPDATE_CART: "UPDATE_CART",
};
